kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-scheduler
  template:
    metadata:
      labels:
        app: kube-scheduler
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kube-scheduler
        image: {{ imageFor "hyperkube" }}
        command:
        - hyperkube
        - kube-scheduler
        args:
        - "--config=/etc/kubernetes/config/config.yaml"
        - "--cert-dir=/var/run/kubernetes"
        - "--port=0"
        - "--authentication-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "--authorization-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "-v=2"
        volumeMounts:
        - mountPath: /etc/kubernetes/secret
          name: secret
        - mountPath: /etc/kubernetes/config
          name: config
        - mountPath: /var/run/kubernetes/
          name: cert
        workDir: /var/run/kubernetes
      volumes:
      - secret:
          secretName: service-admin-kubeconfig
        name: secret
      - configMap:
          name: kube-scheduler-config
        name: config
      - emptyDir: {}
        name: cert
