apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-version-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cluster-version-operator
  template:
    metadata:
      name: cluster-version-operator
      labels:
        k8s-app: cluster-version-operator
    spec:
      tolerations:
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values: ["cluster-version-operator"]
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values: ["cluster-version-operator"]
            topologyKey: "failure-domain.beta.kubernetes.io/zone"
      initContainers:
        - name: setup
          image: quay.io/csrwng/origin-cluster-version-operator:hosted_annotations
          command:
            - "/bin/bash"
          args:
            - "-c"
            - |-
              cp $(which cluster-version-operator) /work/
          volumeMounts:
            - mountPath: /work
              name: work
      containers:
        - name: cluster-version-operator
          image: {{ .ReleaseImage }}
          imagePullPolicy: Always
          command:
            - "/work/cluster-version-operator"
          args:
            - "start"
            - "--release-image={{ .ReleaseImage }}"
            - "--enable-auto-update=false"
            - "--enable-default-cluster-version=true"
            - "--kubeconfig=/etc/openshift/kubeconfig/kubeconfig"
            - "--v=4"
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/cvo/updatepayloads
              name: etc-cvo-updatepayloads
              readOnly: true
            - mountPath: /etc/openshift/kubeconfig
              name: kubeconfig
              readOnly: true
            - mountPath: /work
              name: work
              readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: EXCLUDE_MANIFESTS
              value: internal-openshift-hosted
      volumes:
        - name: work
          emptyDir: {}
        - name: etc-cvo-updatepayloads
          emptyDir: {}
        - name: kubeconfig
          secret:
            secretName: service-network-admin-kubeconfig